version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "ðŸ”€"
    labels: ["github-actions"]
    target-branch: "dev"
    reviewers:
      - "Jarmos-san"
